### ISSUE TITLE
BioSchema:Protein (draft 0,5) redefine PRO in unfortunate ways.

### ISSUE THREAD

**Issue by JervenBolleman** [BioSchemas/specifications#223]
PRO is a class based ontology. Schema.org is instance based.
This leads to the unfortunate consequence that:

```turtle
obo:PR_P00519 rdfs:subClassOf obo:PR_000000001 .
```
becomes
```turtle
obo:PR_P00519 rdf:type obo:PR_000000001 .
```
This means that PRO can't really use BioSchema as it would redefine it's core concepts in an unfortunate manner.

As a long term fix I suggest we mint a new IRI for the bioschema:Protein concept that is much broader than: PR_000000001, uniprot:Protein or CHEBI:36080.

This is a subissue of https://github.com/BioSchemas/specifications/issues/218

**Comment by AlasdairGray** [comment]
Creating more of a Bioschemas set of properties and terms is something that we would need to get wider community agreement on since it is against the current decision of trying to reuse appropriate terms.

However, the argument here about the unfortunately consequences, and the desire to have the types and properties we use understandable to consumers (in particular search engines), is making this something that we will need to decide upon.

**Comment by JervenBolleman** [comment]
@AlasdairGray do you have a pointer to the discussion regarding reuse?

**Comment by AlasdairGray** [comment]
The decision was made on the mailing list in Nov 2017 https://lists.w3.org/Archives/Public/public-bioschemas/2017Nov/0094.html

**Comment by AlasdairGray** [comment]
We now have a new [proposal](https://lists.w3.org/Archives/Public/public-bioschemas/2018Oct/0007.html) that eliminates this problem. It does mean that we need to get the community to agree that we are now needing to propose a larger set of types and properties for schema.org.

**Comment by JervenBolleman** [comment]
@AlasdairGray yes the new proposal solves this issue, if accepted you can close this one.
