### ISSUE TITLE
Should BioChemEntity inherit from schema.org/Intangible?

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#226]
Please use this issue to vote whether the proposal for BioChemEntity should inherit from schema.org/Intangible. You can use:

- Yes or +1 to indicate support for inheriting from schema.org/Intangible
- No or -1 to indicate that BioChemEntity should inherit only from schema.org/Thing

**Comment by mcourtot** [comment]
Could you please add more details as to what this means practically?

**Comment by AlasdairGray** [comment]
For datasets like UniProt, their records represent the concept of a particular protein rather than a specific instance of that protein in the real-world. Inheriting from Intangible means that we are only going to use BioChemEntity for concepts rather than real-world instances.

**Comment by mcourtot** [comment]
Does that imply that we wouldn't need DataRecord? It'd be useful to have a clear idea of the needed changes if we go for Intangible.

**Comment by stain** [comment]
In principle agree on using Intangible, but we then have to update the description:

> A BioChemEntity is any object that exists in the physical world and cannot be better represented with any other existing type in schema.org. This includes theoretical objects that may potentially be invented/created, but do not currently exist. For example, synthetic possible chemicals. 

We can't say intangible things exist in the physical world. But they can describe aspects of things in the physical world.

So `Intangible` would limit `BioChemEntity` so it can no longer be used for describing tangible things "that exists in the physical world" like _biosample `15152-1532` in the freezer_ or _Mouse `1271` born 2018-12-24_. Rather then the intangible biochem entrties can only be for Socrates Cave classes of ideas/concepts, e.g. "Human X chromosome" and "Rattus Norvegius reference genome".  

Generally the schema.org approach is to be open-ended - so I am not sure what we gain by making all  `BioChemEntity` intangible rather than only those subtypes where it makes sense (e.g. `ProteinStructure`)

**Comment by AlasdairGray** [comment]
@stain The definition has been updated to
> Any biological, chemical, or biochemical thing. For example: a protein; a gene; a chemical; a synthetic chemical.

**Comment by AlasdairGray** [comment]
The management group discussed this today. A summary of the discussion is

- No conclusive outcome to the discussion
- Lots of inconsistency within schema.org as to Intangible or not
- Analogous to MedicalEntity
- Intangible gives us restrictions without perceived benefits.

As such, it was decided to inherit directly from Thing.
