### ISSUE TITLE
Gene Definition

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#272]
We need a descriptive definition for the [Gene Type](http://bio.sdo-bioschemas-227516.appspot.com/Gene)

**Comment by deniseOme** [comment]
@ljgarcia, one issue raised at the Paris biohackathon by the lady whose name I can't remember (from Canada? Or US?) is the DNA versus RNA genomes. The majority of the genomes out there from virus to mammals are DNA-based, but there are a few classes of virus that have RNA genomes. 

I can see that from NCBI genomes resource they provide RNA genomes in the DNA nucleotide format (A, C, G, T) instead of RNA nucleotides (out with T, in with U) e.g. https://www.ncbi.nlm.nih.gov/nuccore/701219395

We should seek input from virologists if we want to include RNA genomes or do more research ourselves. Alternatively we may make the deliberate decision to define genes as per DNA genomes only.

For the time being, this is a suggestion:

gene = discrete unit of nucleotide sequences. When in DNA genomes, genes will get transcribed into RNAs, and the mostly translated into proteins.

**Comment by ens-ap5** [comment]
Amendment to above definition: a discrete locus of heritable, genomic sequence which affect an organism's traits https://en.wikipedia.org/wiki/Gene

**Comment by ens-ap5** [comment]
Examples: protein-coding: FOXP2 (Forkhead box protein P2); RNA gene: SCARNA21 (small Cajal body-specific RNA 21).

No examples of viral gene at present.

**Comment by folago** [comment]
At the F2F meeting this definition was agreed upon: 
A discrete unit of inheritance which affects an organism's traits, typically associated with a genomic locus https://en.wikipedia.org/wiki/Gene. Examples include FOXP2 (Forkhead box protein P2), SCARNA21 (small Cajal body-specific RNA 21), A- (agouti genotype).

**Comment by ens-ap5** [comment]
Small tweak to make more generic:

A discrete unit of inheritance which affects one or more biological traits, typically associated with a genomic locus https://en.wikipedia.org/wiki/Gene. Examples include FOXP2 (Forkhead box protein P2), SCARNA21 (small Cajal body-specific RNA 21), A- (agouti genotype).

**Comment by deniseOme** [comment]
I'd recommend refraining from using "genomic locus" in this definition. Locus in genetics and genomics is a location for other entities as well, not only genes. Eg. the word locus can also be applied to SNPs, CNVs or any other region containing one or more genes...

**Comment by AlasdairGray** [comment]
@deniseOme would you suggest just omitting the final part of the sentence so that it would become:

> A discrete unit of inheritance which affects one or more biological traits https://en.wikipedia.org/wiki/Gene. Examples include FOXP2 (Forkhead box protein P2), SCARNA21 (small Cajal body-specific RNA 21), A- (agouti genotype).

@ens-ap5 @folago what do you think of this alternative?

**Comment by deniseOme** [comment]
Yes @AlasdairGray, I think this alternative is a safer bet.

**Comment by folago** [comment]
@AlasdairGray @deniseOme yes the suggested edit looks good to me.
