### ISSUE TITLE
Capture arbitrary ancestor/descendant of a Taxon

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#324]
Previously had a request to capture an ancestor/descendant of a Taxon but not the immediate parent/child. This was captured in a draft but has not made it across into the release one version of Taxon. To be considered for the next release unless there is agreement to push it into release one prior to submission to schema.org.

Definitions:
```
  <div typeof="rdf:Property" resource="http://schema.org/ancestorTaxon">
      <link property="http://schema.org/isPartOf" href="http://bio.schema.org" />
      <span class="h" property="rdfs:label">ancestorTaxon</span>
      <span property="rdfs:comment">An ancestor taxa of the taxon in question, but not the closest parent. </span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Taxon">Taxon</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Taxon">Taxon</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Text">Text</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/URL">URL</a></span>
      <link property="http://schema.org/inverseOf" href="http://schema.org/descendantTaxon"/>
      <span>Source:  <a property="dc:source" href="http://www.bioschemas.org/Taxon">Taxon</a></span>
  </div>

  <div typeof="rdf:Property" resource="http://schema.org/descendantTaxon">
      <link property="http://schema.org/isPartOf" href="http://bio.schema.org" />
      <span class="h" property="rdfs:label">descendantTaxon</span>
      <span property="rdfs:comment">A descendant taxa of the taxon in question, but not the closest descendant.</span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Taxon">Taxon</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Taxon">Taxon</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Text">Text</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/URL">URL</a></span>
      <link property="http://schema.org/inverseOf" href="http://schema.org/ancestorTaxon"/>
      <span>Source:  <a property="dc:source" href="http://www.bioschemas.org/Taxon">Taxon</a></span>
  </div>
```

**Comment by frmichel** [comment]
Hi @AlasdairGray, was there any associated description of the reasons for such properties?

Franck.

**Comment by qgroom** [comment]
I'm not certain this is necessary.
replacing the parent/child and the ancestor/descendant terminology with supertaxon/subtaxon would probably solve the problem. supertaxon/subtaxon is neutral on the number of steps in the classification and it also avoids confusion, because organisms genuinely can have parents, children, ancestors and descendants.

**Comment by frmichel** [comment]
I'm not so sure replacing the current parent/child terms with generic terms would help. 

From what I have seen, what matters most to understand the full circumscription is the direct parent/children.  If we only use the supertaxon/subtaxon properties, how to get the direct parent? In some cases, a genus has as parent a family. But according to another taxonomy, the same genus may have as a parent a sub-family. So, to find out the direct parent, one should not just look for a supertaxon with rank family, but for all the supertaxa and select the one with the lowest rank. This requires some sort of reasoning, which is not what I would expect from a vocabulary that intends to be simple.

Also, all taxonomies I've been through model the direct parent and children, and optionally the ancestor/descendant with other dedicated properties like "genus", "family" etc. The latter is however not such a good idea since the "genus" property bears two meanings in that case: the parent taxon, and the taxonomic rank thereof, whereas we have a separate property for the rank.

Anyway, I would still stick to the parent/child properties for now, leaving it open to add ancestor/descendant properties in a later stage.

What do you guys think?

Franck.

**Comment by AlasdairGray** [comment]
The motivation for the ancestor/descendant properties is to allow for the identification for an important ancestor rather than have to traverse the entire tree. I think this came out of the BioHackathon 2018.

**Comment by qgroom** [comment]
Given that schemas will not be trying to reconstruct all of formal taxonomy I'd be fine with parent/child for now. People will doubtlessly use these terms for non-adjacent ranks anyway.

The taxonomic rank property is interesting, because this could be considered a property of a taxonomic name, rather than the taxon.
