### ISSUE TITLE
Should keywords/tags be mandatory?

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#392]
If they are optional, it may be difficult to search. Alternatively, people may enter rubbish keywords.

**Comment by nsjuty** [comment]
I think we should ask for minimum of 1 keyword, and up to 5.
We can make it easier by providing dropdown/autocomplete, predefined terms from selected vocabularies/EDAM

**Comment by AlasdairGray** [comment]
`keywords` is a funny one since the property name is plural and the expected type is `Text`. Therefore, the cardinality should be 'ONE'. You can add a comment that the values should be taken from the labels of the EDAM vocabulary terms.

You may also want to use `about` to indicate using URIs the same terms.

**Comment by stuzart** [comment]
I don't think they should be mandatory. It would mean any registry/repository storing and describing workflows, or workflow description formats, would have to enforce keywords and I don't think this is practical. I'd prefer **Recommended**.

**Comment by alaninmcr** [comment]
recommended one (they are comma separated)
