### ISSUE TITLE
Do we need to connect a TaxonName back to a Taxon?

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#429]
This was raised as a question towards the finalising of the 0.1-DRAFT of TaxonName (see [PR253](https://github.com/BioSchemas/bioschemas.github.io/pull/253#issuecomment-641911945)).

A suggestion was to use `about` as an optional property to connect the two.

**Comment by mjy** [comment]
The link does not belong with TaxonName because TaxonName can be used for many Taxon concepts.

**Comment by qgroom** [comment]
I think @mjy is right. Keeping them separate will perhaps also help to reinforce the difference between them.

**Comment by ljgarcia** [comment]
Hi @frmichel any news about this issue? Thanks

**Comment by frmichel** [comment]
Hi @ljgarcia, sorry I missed this one. 
I agree with @qgroom and @mjy. Depending on the circumscription of a taxon, it is assigned different names: a reference or accepted name, and multiple other names, the synonyms. Since not everybody agrees on the circumscription of a given taxon, linking from the taxon to the names leaves room for various opinions. But linking from the name to the taxon would mix up multiple opinions. 
So I guess we can close this issue. Feel free to reopen if needed.
