### ISSUE TITLE
reagentsUsed

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#442]
The list of reagents used is really very long for certain fermentations. Are **all** reagents expected to be listed? If not, how are those to be listed determined? Some guidance is needed.

**Comment by ljgarcia** [comment]
@alaninmcr having reproducibility in mind, I would say all reagents should be listed but I am not familiar at all with fermentations. What would be your advice there? Is there any alternative to listing them all?
Depending on your insights, @oxgiraldo would adapt the description for the property.

**Comment by alaninmcr** [comment]
My reviewer says:

**It all depends on the format needed to input the data.
If one has to enter one by one, it is really tedious.
Maybe we could limit to macroconstituents and/or refer to literature reference for full details?

Or maybe I would need a definition of 'reagent'?
Do we consider all components that make up a fermentation medium as 'reagent' (can easily be 20 chemicals) or for instance only the type of base we add for pH control?**

**Comment by oxgiraldo** [comment]
**@alaninmcr**, A reagent is defined in CHEBI as “[A substance used in a chemical reaction to detect, measure, examine, or produce other substances](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:33893)”. This means that one should list reagents purchased ready-to-use in a step of a protocol. In addition, there should be a list of  solutions prepared in the lab (for example: HEPES solution: 7.2 g HEPES in ~25 mL of 1xHBSS to final volume of 30 mL),  buffers and media. The section REAGENTS in [this protocol](https://protocolexchange.researchsquare.com/article/pex-616/v1) is an example about how the different types of reagents could be listed.

How to input data also depends on the UI and the UX. But in every lab around the world one always must know and list in the lab book ALL reagents no matter how tedious. This is simply a must, or at lest it was for me when I was a bench biologist.  If all reagents are not listed and well known and documented somewhere then there is a chance that reproducibility is compromised. Exhaustive reporting, e.g. for reagents, is a must in a lab, not an option. In addition, if within a lab one wants to reproduce and experiment then whenever there is no exhaustive information (e.g. recipes for buffers, etc) then one can always ask the person who did the experiment. The problem is that this is not possible if u don't have access to that person. So as a general rule one should always have a clear and comprehensive record that allows anyone to recreate an experiment. I suggest that you check with a person who has lab experience, not computational lab but hands on bench bio lab experience.  

One could also, in an exhaustive and comprehensive way link to IDs that are resolvable (and that have the information needed). This could be if we had such IDs. in the case of a published paper if there is a DOI then this could be used.  If there are no IDs, reliable, real, with all the information, then incomplete information is very close to no information for reproducibility purposes.  In this way one ends up having IDs whenever available as well as traditional text based lists.

**Comment by AlasdairGray** [comment]
Will a reagent always be a chemical substance? If so can we make the range ChemicalSubstance within the profile? 

At the very least I think that we should extend the property to have ChemicalSubstance and possibly MolecularEntity in the range on the type definition.

**Comment by oxgiraldo** [comment]
**@AlasdairGray** Good point, we should extend the property reagentUsed including ChemicalSubstance and MolecularEntity as range.

**Comment by ljgarcia** [comment]
@oxgiraldo @alaninmcr @AlasdairGray to summarize, I would propose the following changes:

1. Add (or point) to the reagent definition in ChEBI
2.  For reproducibility purposes, keep the property as minimum (I am not a wet-lab person but find an analogy here to software, not matter how many dependencies I have in my software, if I do not include them all somehow, together with corresponding versions, there is the risk no one can (re)use my software as there will be broken links to dependencies and then the software might not even compile)
3. Leave to users to decide how many reagents they add there. Please note that nothing is needed for this to happen, the property is minimum and takes MANY, so many can be one or two or a comprehensive list of all used reagents. 
4. Add MolecularEntity and ChemicalSubstance to the range list

Does it sound like we have a plan?

**Comment by oxgiraldo** [comment]
I agree **@ljgarcia**, the property should include the points 1 and 4; and keep this property as minimum and takes MANY.

**Comment by gtsueng** [comment]
This appears to have been addressed by https://github.com/BioSchemas/bioschemas.github.io/pull/320. Unless @oxgiraldo suggests otherwise, it will be closed.

**Comment by ljgarcia** [comment]
We can close this one as well, thanks @gtsueng
