### ISSUE TITLE
Update and refresh existing tutorials

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#488]
Tutorials have now been migrated from the GitBook to the Bioschemas website, and markup is embedded within them.

We need to ensure that the content is correct and up to date.

_Originally posted by @AlasdairGray in https://github.com/BioSchemas/specifications/issues/479#issuecomment-780410287_

**Comment by ljgarcia** [comment]
To the best of my knowledge, they are correct and up to date regarding what was in the GitBook.
Now, for the actual content, I suggest someone else to try them out and raise issues. Having one volunteer per page would be great so the volunteer has time to go through it without rushing.

**Comment by ljgarcia** [comment]
I suggest to go through the content as follows: 
- [x] https://bioschemas.org/tutorials/what_why_schema --> @AlasdairGray 
- [x] https://bioschemas.org/tutorials/markup_examples --> @alaninmcr 
- [x] https://bioschemas.org/tutorials/what_why_bioschemas --> @nsjuty 
- [x] https://bioschemas.org/tutorials/howto/howto_right_profile --> @frmichel 
- [x] https://bioschemas.org/tutorials/howto/howto_add_markup  --> @aurel-l 
- [x] https://bioschemas.org/tutorials/howto/howto_add_github --> @albangaignard 
- [x] https://bioschemas.org/tutorials/howto/howto_check_deploy --> @ivanmicetic 

If you see minor things that you can directly solve via PR (e.g., typos, wording), please go ahead. Otherwise please create an issue with the label topic:TrainingPortal 

If you cannot do the review by the next community meeting on the 26th of April, please let us know if the 24th of May would work for you as deadline; otherwise nominate someone else and ping her/him here. Try and avoid nominating someone who is already nominated. Thanks!

**Comment by nsjuty** [comment]
modified the what/why text to mention EOSC rathet than just focus on schema.org adoption

**Comment by ljgarcia** [comment]
@nsjuty Please create the corresponding PR for the correction you propose. Thanks!

**Comment by AlasdairGray** [comment]
@ivanmicetic check will be complete when [PR404](https://github.com/BioSchemas/bioschemas.github.io/pull/404) is accepted
_Seems quite appropriate that a 404 error is going to be fixed by PR404 :p_

**Comment by AlasdairGray** [comment]
@aurel-l any update on the review of the [How to add markup tutorial](https://bioschemas.org/tutorials/howto/howto_add_markup)? The action in the last community call was that an issue was to be created; has this been done?

- [x] Need to cover basic properties being proposed in #294

**Comment by AlasdairGray** [comment]
At the [community call on 28 June 2021](https://docs.google.com/document/d/1kd5F97ogdiPNhLTnkei-RVR8TC8Ohpc5QSPX3KsfDrk/edit#heading=h.98egkfgjx50f) the following issues were identified with a brief scan of the [How to add markup tutorial](https://bioschemas.org/tutorials/howto/howto_add_markup):
- It's not long enough (@nsjuty / @AlasdairGray )
- Missing statement on **where** the content needs to be added, and **what** creates that HTML (@egonw )
- Where to put the JSON-LD in the HTML page? Multiple places in cases of multiple objects (@egonw )

**Comment by ljgarcia** [comment]
> 
> 
> At the [community call on 28 June 2021](https://docs.google.com/document/d/1kd5F97ogdiPNhLTnkei-RVR8TC8Ohpc5QSPX3KsfDrk/edit#heading=h.98egkfgjx50f) the following issues were identified with a brief scan of the [How to add markup tutorial](https://bioschemas.org/tutorials/howto/howto_add_markup):
> 
>     * It's not long enough (@nsjuty / @AlasdairGray )
> 
>     * Missing statement on **where** the content needs to be added, and **what** creates that HTML (@egonw )
> 
>     * Where to put the JSON-LD in the HTML page? Multiple places in cases of multiple objects (@egonw )

Please see PR https://github.com/BioSchemas/bioschemas.github.io/pull/447
