### ISSUE TITLE
Protein 0.11 links to 404 DNA and RNA

### ISSUE THREAD

**Issue by egonw** [BioSchemas/specifications#500]
It think these were both deprecated for BioChemEntity, right? 

![image](https://user-images.githubusercontent.com/26721/118406972-b690a780-b67e-11eb-9f57-8b4722081912.png)

**Comment by AlasdairGray** [comment]
Both types still exist but are in DRAFT status, not release, so were not included in the first Schema.org proposal. However, the types are missing an active working group and so could well be deprecated.

The issue here are some missing redirects. These have been fixed in [PR430](https://github.com/BioSchemas/bioschemas.github.io/pull/430).
