### ISSUE TITLE
Incomplete Bioschemas profile URL (DDE)

### ISSUE THREAD

**Issue by thomasrosnet** [BioSchemas/specifications#636]
Hello,

Some profiles in the DDE [JSONLD](https://github.com/BioSchemas/bioschemas-dde/blob/main/bioschemas.json) specs, have the [schema:schemaVersion] property not properly pointing to the corresponding Bioschemas profile webpage.
As follows, DataCatalog and Sample profiles referenced in [DDE](https://github.com/BioSchemas/bioschemas-dde/blob/main/bioschemas.json) are invalid (http 404 not found errors):
- https://bioschemas.org/profiles/DataCatalog/0.3-RELEASE
- https://bioschemas.org/profiles/Sample/0.2-RELEASE

They should maybe refer to the Bioschemas website profiles:
- https://bioschemas.org/profiles/DataCatalog/0.3-RELEASE-2019_07_01
- https://bioschemas.org/profiles/Sample/0.2-RELEASE-2018_11_10

Is it an error in the DDE jsonld file found at https://github.com/BioSchemas/bioschemas-dde/blob/main/bioschemas.json through the schema:schemaVersion property ?

@albangaignard

**Comment by gtsueng** [comment]
Thanks for identifying this issue, @thomasrosnet . The `schemaVersion` is automatically populated in the DDE based on the name of the JSON-LD file in the specifications repository. At the time these two files were made, the dates had been removed due to confusion about the use of dates in the version. Updating the file name should address this issue.
