### ISSUE TITLE
bioschemas.org shows a 404

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#66]
pointing to http://bioschemas.github.io/ which does not exist

**Comment by martin-nc** [comment]
Pushed it back to the old url now (http://bioschemas.github.io/bioschemas).

**Comment by njall** [comment]
It looks like you've set the page up as a Project page rather than an Organization page so the github.io URL will have /<projectName> after it https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages

http://bioschemas.org currently redirects to the http://bioschemas.github.io/bioschemas page.
To deliver the page under the http://bioschemas.org URL without redirecting, you need to follow these steps:
https://help.github.com/articles/adding-a-cname-file-to-your-repository/

**Comment by martin-nc** [comment]
Oh yes - I wasn't sure which way to go when I set it up. I also hadn't noticed that GitHub recommends using subdomains. They hammer on about it quite a bit:

>  We strongly recommend that you use a custom subdomain for these reasons:
> -  It gives your GitHub Pages site the benefit of our Content Delivery Network.
> - It will not be affected by changes in the underlying IP addresses of GitHub's servers.
> - Pages will load significantly faster because Denial of Service protection can be implemented more efficiently.

Perhaps we should take their advice?

**Comment by martin-nc** [comment]
Fixed this.
