### ISSUE TITLE
Create a google calendar that we could embed in the website

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#75]

**Comment by robertopreste** [comment]
I just added a Bioschemas Google Calendar to the [Meetings](http://bioschemas.org/meetings/index.html) (it's one of the former pages of the website, just using it as a test page). We can edit colors, dimensions and other stuff, so I was thinking that we could make it smaller and embed it in a sidebar on the home page?

**Comment by rajido** [comment]
That's great, thanks. BTW it seems the old menu is rendering in the meeting page.

**Comment by robertopreste** [comment]
Yes, that's because the Meetings page is part of the "old" website, I just used it as a test page to show you the calendar, and it's not displayed in the current version. I will leave the calendar there and restore the redirection to the home page, we can think about that later when we build the sidebar.

**Comment by rajido** [comment]
OK, thanks!

**Comment by rajido** [comment]
I just checked and it seems the calendar is associated to admin@bioschemas.org, how difficult would be to change it to community@bioschemas.org ? It would be great if the community goup members could create events anytime they want, is this possible?

**Comment by AlasdairGray** [comment]
I'm closing this issue as it does not seem relevant any more.
